[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
<<<<<<< HEAD
  HUGO_VERSION = "0.91.2"
=======
  HUGO_VERSION = "0.58.0"
>>>>>>> my-site
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
